name: Auto Sign In
on:
  schedule:
    - cron: '5 16 * * *'  # 每天UTC时间16:05运行，即北京时间00:05
  workflow_dispatch:      # 允许手动触发
jobs:
  signin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@latest
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master
      
    - name: Check Chrome and ChromeDriver versions
      run: |
        google-chrome --version
        chromedriver --version
        
    - name: Run sign-in script
      env:
        COOKIE: ${{ secrets.COOKIE }}
        IYUU_TOKEN: ${{ secrets.IYUU_TOKEN }}
      run: python sign.py
